DROP DATABASE IF EXISTS SIMPSONS;
CREATE DATABASE SIMPSONS CHARSET utf8mb4;
USE SIMPSONS;

CREATE TABLE CHARACTERS (
  ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  AGE INT(3) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CHARACTERS(NAME, AGE, EMAIL) VALUES ("Homer Simpson", "36", "homer@simpsons.com");
INSERT INTO CHARACTERS(NAME, AGE, EMAIL) VALUES ("Marge Simpson", "34", "marge@simpsons.com");
INSERT INTO CHARACTERS(NAME, AGE, EMAIL) VALUES ("Bart Simpson", "10", "bart@simpsons.com");
INSERT INTO CHARACTERS(NAME, AGE, EMAIL) VALUES ("Lisa Simpson", "8", "lisa@simpsons.com");
INSERT INTO CHARACTERS(NAME, AGE, EMAIL) VALUES ("Maggie Simpson", "1", "maggie@simpsons.com");
