START TRANSACTION;

DROP DATABASE IF EXISTS SIMPSONS;
CREATE DATABASE SIMPSONS CHARSET utf8mb4;
USE SIMPSONS;

CREATE TABLE CHARACTERS (
  ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  SURNAME VARCHAR (100) NOT NULL
);

INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Homer", "Simpsons");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Marge", "Simpsons");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Bart", "Simpsons");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Lisa", "Simpsons");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Maggie", "Simpsons");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Ned", "Flanders");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Maude", "Flanders");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Milhouse", "Van Houten");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Luann", "Van Houten");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Montgomery", "Burns");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Waylon", "Smithers");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Moe", "Szyslak");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Seymour", "Skinner");
INSERT INTO CHARACTERS(NAME, SURNAME) VALUES("Edna", "Krabappel");

COMMIT;
