apiVersion: v1
kind: PersistentVolume
metadata:
  name: poc-volume-persistent-01
  labels:
    poc: poc-volume-persistent
    type: local
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/vagrant/poc-volume-persistent-01"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: poc-volume-persistent-02
  labels:
    poc: poc-volume-persistent
    type: local
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/vagrant/poc-volume-persistent-02"
