version: '3'
services:
  db:
    container_name: poc_guacamole_mysql
    image: mysql:5.7
    env_file: common.env
    volumes:
      - $PWD/conf/init-db.sql:/docker-entrypoint-initdb.d/initdb.sql
      - guacamole-data:/var/lib/mysql
    networks:
      - network
  daemon:
    container_name: poc_guacamole_daemon
    image: guacamole/guacd:1.2.0
    networks:
      - network
    depends_on:
      - db
  web:
    container_name: poc_guacamole_web
    image: guacamole/guacamole:1.2.0
    env_file: common.env
    networks:
      - network
    #restart: always
    depends_on:
      - daemon
  proxy:
    container_name: poc_guacamole_proxy
    image: nginx
    ports:
      - "80:80"
    volumes:
      - $PWD/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network
    #restart: always
    depends_on:
      - web
volumes:
  guacamole-data:
networks:
  network:
