version: '3'
services:
  machine_jenkins:
    container_name: poc_server_jenkins
    image: poc-jenkins:docker
    build:
      context: dockerfiles
      dockerfile: dockerfile-jenkins-docker
    ports:
      - "8080:8080"
    volumes:
      - $PWD/mount/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network

  machine_jenkins_agent:
    container_name: poc_server_jenkins_agent_ssh
    image: poc-jenkins:ssh-agent
    build:
      context: dockerfiles
      dockerfile: dockerfile-jenkins-agent-ssh
    env_file: $PWD/tmp/common.env
    networks:
      - network


  machine_gitlab:
    container_name: poc_server_gitlab
    hostname: gitlab.example.com
    image: gitlab/gitlab-ce:12.6.8-ce.0
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "$PWD/mount/gitlab/config:/etc/gitlab"
      - "$PWD/mount/gitlab/logs:/var/log/gitlab"
      - "$PWD/mount/gitlab/data:/var/opt/gitlab"
    networks:
      - network

  machine_registry_docker:
    container_name: poc_server_registry_docker
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - $PWD/mount/docker-registry/:/var/lib/registry
    networks:
      - network

  machine_ssh:
    container_name: poc_server_ssh
    image: poc-centos-server-ssh:keys
    networks:
      - network

networks:
  network:
