apiVersion: v1
kind: Pod
metadata:
  labels:
    poc: poc-probe-liveness
  name: poc-probe-liveness
spec:
  containers:
  - name: poc-probe-liveness
    image: alpine # k8s.gcr.io/busybox
    #image: k8s.gcr.io/goproxy:0.1
    #image: k8s.gcr.io/liveness
    imagePullPolicy: IfNotPresent
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 10; rm -f /tmp/healthy; sleep 600

    # A first type of liveness probe uses a command
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 3
      periodSeconds: 3

    # A second type of liveness probe uses a TCP socket
    #livenessProbe:
    #  tcpSocket:
    #    port: 8080
    #  initialDelaySeconds: 15
    #  periodSeconds: 20

    # A third type of liveness probe uses a HTTP request
    #livenessProbe:
    #  httpGet:
    #    path: /healthz
    #    port: 8080
    #    httpHeaders:
    #    - name: Custom-Header
    #      value: Awesome
    #  initialDelaySeconds: 3
    #  periodSeconds: 3
