apiVersion: v1
kind: ConfigMap
metadata:
  name: poc-configmap-environment-file
  labels:
    poc: poc-configmap-environment-file
data:
  CHARACTER: "un erizo."
  SLEEP_TIME: "2s"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-configmap-environment-file
  labels:
    poc: poc-configmap-environment-file
spec:
  replicas: 1
  selector:
    matchLabels:
      poc: poc-configmap-environment-file
  template:
    metadata:
      labels:
        poc: poc-configmap-environment-file
    spec:
      containers:
        - name: poc-app-message-loop
          image: kalpeva/poc-golang-loop-message:1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: poc-configmap-environment-file
