apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: poc-replicaset
  labels:
    poc: poc-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      poc: poc-replicaset
  template:
    metadata:
      labels:
        poc: poc-replicaset
        language: golang
    spec:
      containers:
        - name: poc-app-message-loop
          image: kalpeva/poc-golang-message-loop:1.0
          env:
            - name: CHARACTER
              value: "un arquero."
            - name: SLEEP_TIME
              value: "3s"
