FROM jenkins/ssh-agent:jdk11

LABEL version="1.0" maintainer="<kalpeva@gmail.com>"

# Fix: add PATH to /etc/environment
RUN echo PATH=$PATH >> /etc/environment

# Install maven
RUN apt-get update && \
    apt-get install --assume-yes maven

# Install git
RUN apt-get install --assume-yes git
