apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-restrict-resources-for-containers-01
  namespace: poc-restrict-resources-for-containers-ns
  labels:
    app: poc-client
    poc: poc-restrict-resources-for-containers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-client-01
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: poc-client-01
        poc: poc-restrict-resources-for-containers
    spec:
      containers:
        - name: poc-app-loop-message-1
          image: kalpeva/poc-golang-loop-message:1.0
          imagePullPolicy: Always
          env:
            - name: CHARACTER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SLEEP_TIME
              value: "5s"
        - name: poc-app-message-loop-2
          image: kalpeva/poc-golang-loop-message:1.0
          imagePullPolicy: Always
          env:
            - name: CHARACTER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SLEEP_TIME
              value: "1s"
          resources:
            requests:
              cpu: 40m
              memory: 40Mi
            limits:
              cpu: 40m
              memory: 40Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-restrict-resources-for-containers-02
  namespace: poc-restrict-resources-for-containers-ns
  labels:
    app: poc-client
    poc: poc-restrict-resources-for-containers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-client-02
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: poc-client-02
        poc: poc-restrict-resources-for-containers
    spec:
      containers:
          - name: poc-app-message-loop-3
            image: kalpeva/poc-golang-loop-message:1.0
            imagePullPolicy: Always
            env:
              - name: CHARACTER
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: SLEEP_TIME
                value: "2s"
            resources:
              requests:
                cpu: 60m
                memory: 60Mi
              limits:
                cpu: 100m
                memory: 100Mi
