apiVersion: v1
kind: Namespace
metadata:
  name: poc-restrict-resources-for-containers-ns
  labels:
    poc: poc-restrict-resources-for-containers
---
apiVersion: v1
kind: LimitRange
metadata:
  name: poc-restrict-resources-for-containers
  namespace: poc-restrict-resources-for-containers-ns
spec:
  limits:
  - default:
      cpu: 30m
      memory: 30Mi
    defaultRequest:
      cpu: 20m
      memory: 20Mi
    max:
      cpu: 50m
      memory: 50Mi
    min:
      cpu: 10m
      memory: 10Mi
    type: Container
