apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-deployment-scale-manual
  labels:
    poc: poc-deployment-scale-manual
spec:
  replicas: 8
  selector:
    matchLabels:
      poc: poc-deployment-scale-manual
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        poc: poc-deployment-scale-manual
        language: golang
    spec:
      containers:
        - name: poc-app-message-loop
          image: kalpeva/poc-golang-loop-message:1.0
          env:
            - name: CHARACTER
              value: "un tractor amarillo."
            - name: SLEEP_TIME
              value: "2s"
