job("poc-app-maven-autogenerated") {
  description("Proof of concept about create job for create app with maven")

  scm {
    git('https://github.com/jenkins-docs/simple-java-maven-app.git', 'master', {node -> node / 'extensions' << '' })
  }

   steps {
        maven {
            mavenInstallation('maven-3.8.5')
            goals('-B -DskipTests clean package')
        }

        maven {
            mavenInstallation('maven-3.8.5')
            goals('test')
        }

        shell('''
            echo "*************************"
            echo "***** Deploying jar *****"
            echo "*************************"
            java -jar /var/jenkins_home/workspace/poc-app-maven-autogenerated/target/my-app-1.0-SNAPSHOT.jar
        ''')
    }

    publishers {
      archiveArtifacts {
        pattern('target/*.jar')
        onlyIfSuccessful()
      }
      archiveJunit('target/surefire-reports/*.xml')
      mailer('hyeepaa@gmail.com', false, true)
    }
}
