# server application namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ns-server
  labels:
    poc: poc-service-cluster-ip-between-namespaces
---
# server application service
apiVersion: v1
kind: Service
metadata:
  name: poc-service
  namespace: ns-server
  labels:
    poc: poc-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: poc-server
  ports:
    - port: 9000
      protocol: TCP
      targetPort: http-server
---
# server application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-server
  namespace: ns-server
  labels:
    app: poc-server
    poc: poc-service-cluster-ip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poc-server
  template:
    metadata:
      labels:
        app: poc-server
        poc: poc-service-cluster-ip
    spec:
      containers:
        - name: server
          image: kalpeva/poc-golang-server-client:1.0
          command:
            - server
          ports:
            - name: http-server
              containerPort: 8000
---
# client application namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ns-client
  labels:
    poc: poc-service-cluster-ip-between-namespaces
---
# client application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-client
  namespace: ns-client
  labels:
    app: poc-client
    poc: poc-service-cluster-ip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-client
  template:
    metadata:
      labels:
        app: poc-client
        poc: poc-service-cluster-ip
    spec:
      containers:
        - name: client
          image: kalpeva/poc-golang-server-client:1.0
          command:
            - client
          env:
            - name: SERVER_URL
              value: "http://poc-service.ns-server:9000"
            - name: ENDPOINT
              value: "/echo"
            - name: SLEEP_TIME
              value: "3s"
