apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-rbac-service-account
  labels:
    app: rbac
  namespace: poc-rbac-service-account-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rbac
    spec:
      serviceAccountName: developer
      containers:
        - name: poc-app-access-k8s
          image: kalpeva/poc-golang-access-k8s:1.0
