apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-rbac-service-account
  labels:
    poc: poc-rbac-service-account
  namespace: poc-rbac-service-account-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      poc: poc-rbac-service-account
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        poc: poc-rbac-service-account
    spec:
      serviceAccountName: poc-rbac-service-account
      containers:
        - name: poc-app-access-k8s
          image: kalpeva/poc-golang-access-k8s:1.0
          env:
            - name: NAMESPACE
              value: "poc-rbac-service-account-ns"
            - name: SLEEP_TIME
              value: "3s"
