apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: poc-rbac-service-account
  labels:
    poc: poc-rbac-service-account
  namespace: poc-rbac-service-account-ns
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
