apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: poc-rbac-service-account
  labels:
    poc: poc-rbac-service-account
  namespace: poc-rbac-service-account-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: poc-rbac-service-account
subjects:
- kind: ServiceAccount
  name: poc-rbac-service-account
  namespace: poc-rbac-service-account-ns
