START TRANSACTION;
DROP DATABASE IF EXISTS CYCLING;
CREATE DATABASE CYCLING CHARSET utf8mb4;
USE CYCLING;

CREATE TABLE TEAM (
  ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL
);

CREATE TABLE RIDER (
  ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  SURNAME VARCHAR (100) NOT NULL,
  TEAM_ID INT UNSIGNED NOT NULL,
  FOREIGN KEY(TEAM_ID) REFERENCES TEAM(ID)
);

INSERT INTO TEAM(ID, NAME) VALUES (1, "UAE Team Emirates");
INSERT INTO TEAM(ID, NAME) VALUES (2, "Jumbo-Visma");
INSERT INTO TEAM(ID, NAME) VALUES(3, "EF Pro Cycling");
INSERT INTO TEAM(ID, NAME) VALUES(4, "Ineos Grenadiers");
INSERT INTO TEAM(ID, NAME) VALUES(5, "ITrek-Segafredo");

INSERT INTO RIDER(ID, NAME, SURNAME, TEAM_ID) VALUES(1, "Tadej", "Pogacar", 1);
INSERT INTO RIDER(ID, NAME, SURNAME, TEAM_ID) VALUES(2, "Tom", "Dumoulin", 2);
INSERT INTO RIDER(ID, NAME, SURNAME, TEAM_ID) VALUES(3, "Primoz", "Roglic", 2);
INSERT INTO RIDER(ID, NAME, SURNAME, TEAM_ID) VALUES(4, "Rigoberto", "Uran", 3);
INSERT INTO RIDER(ID, NAME, SURNAME, TEAM_ID) VALUES(5, "Richard", "Carapaz", 4);
INSERT INTO RIDER(ID, NAME, SURNAME, TEAM_ID) VALUES(6, "Richie", "Port", 5);
INSERT INTO RIDER(ID, NAME, SURNAME, TEAM_ID) VALUES(7, "Wilco", "Kelderman", 5);
COMMIT;
