apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-secret-as-environment-key
  labels:
    poc: poc-secret-as-environment-key
spec:
  replicas: 1
  selector:
    matchLabels:
      poc: poc-secret-as-environment-key
  template:
    metadata:
      labels:
        poc: poc-secret-as-environment-key
    spec:
      containers:
        - name: poc-app-message-loop
          image: kalpeva/poc-golang-loop-message:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: CHARACTER
              valueFrom:
                secretKeyRef:
                  name: poc-secret-as-environment-key
                  key: hidden-place
