apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
data:
{{- range $path, $_ :=  .Files.Glob  "resources/scripts/**.sql" }}
  {{ $path | trimPrefix "resources/scripts/" }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
