apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-initialization
  namespace: {{ .Release.Namespace }}
data:
{{- range $path, $_ :=  .Files.Glob  "scripts/initial/**.sql" }}
  {{ $path | trimPrefix "scripts/initial/" }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
