apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poc-rbac-clusterrole
  labels:
    poc: poc-rbac-authorization
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
