version: '3'
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
  cadence-server:
    image: ubercadence/server:master-auto-setup
    ports:
     - "8000:8000"
     - "8001:8001"
     - "8002:8002"
     - "8003:8003"
     - "7933:7933"
     - "7934:7934"
     - "7935:7935"
     - "7939:7939"
     - "7833:7833"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "PROMETHEUS_ENDPOINT_0=0.0.0.0:8000"
      - "PROMETHEUS_ENDPOINT_1=0.0.0.0:8001"
      - "PROMETHEUS_ENDPOINT_2=0.0.0.0:8002"
      - "PROMETHEUS_ENDPOINT_3=0.0.0.0:8003"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
      - prometheus
  cadence-web:
    image: ubercadence/web:latest
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence-server:7933"
    ports:
      - "8089:8088"
    depends_on:
      - cadence-server
  grafana:
    image: grafana/grafana
    user: "1000"
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
  webapp-shopping:
    image: kalpeva/api-shopping:latest
    user: "1000"
    ports:
      - '7090:8080'
  api-order:
    image: kalpeva/api-order:latest
    user: "1000"
    ports:
      - '7091:8080'
  api-inventory:
    image: kalpeva/api-inventory:latest
    user: "1000"
    ports:
      - '7092:8080'
  api-payment:
    image: kalpeva/api-payment:latest
    user: "1000"
    ports:
      - '7093:8085'
  api-shipping:
    image: kalpeva/api-shipping:latest
    user: "1000"
    ports:
      - '7094:8080'
  api-notification:
    image: kalpeva/api-notification:latest
    user: "1000"
    ports:
      - '7095:9090'


