START TRANSACTION;

DROP DATABASE IF EXISTS LIBRARY;
CREATE DATABASE LIBRARY CHARSET utf8mb4;
USE LIBRARY;

CREATE TABLE AUTHOR (
  ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  SURNAME VARCHAR(100) NOT NULL
);

CREATE TABLE BOOK (
  ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(100) NOT NULL,
  AUTHOR_ID INT UNSIGNED NOT NULL,
  FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(ID)
);

INSERT INTO AUTHOR(ID, NAME, SURNAME) VALUES(1, "Gustavo Adolfo", "Bécquer");
INSERT INTO AUTHOR(ID, NAME, SURNAME) VALUES(2, "Yuval Noah", "Harari");
INSERT INTO AUTHOR(ID, NAME, SURNAME) VALUES(3, "Jesus", "Mosterín");
INSERT INTO AUTHOR(ID, NAME, SURNAME) VALUES(4, "Pablo", "Alcalde San Miguel");
INSERT INTO AUTHOR(ID, NAME, SURNAME) VALUES(5, "Albert", "Vázquez");
INSERT INTO AUTHOR(ID, NAME, SURNAME) VALUES(6, "José", "Calvo Poyato");
INSERT INTO AUTHOR(ID, NAME, SURNAME) VALUES(7, "Ignasi", "Serrahima");

INSERT INTO BOOK(ID, TITLE, AUTHOR_ID) VALUES(1, "Leyendas", 1);
INSERT INTO BOOK(ID, TITLE, AUTHOR_ID) VALUES(2, "Sapiens", 2);
INSERT INTO BOOK(ID, TITLE, AUTHOR_ID) VALUES(3, "¡Vivan los animales!", 3);
INSERT INTO BOOK(ID, TITLE, AUTHOR_ID) VALUES(4, "Electrónica aplicada", 4);
INSERT INTO BOOK(ID, TITLE, AUTHOR_ID) VALUES(5, "Poniente", 5);
INSERT INTO BOOK(ID, TITLE, AUTHOR_ID) VALUES(6, "La Ruta Infinita", 6);
INSERT INTO BOOK(ID, TITLE, AUTHOR_ID) VALUES(7, "El Mapa del fin del mundo", 7);

COMMIT;
