apiVersion: v1
kind: Pod
metadata:
  name: poc-pod-environment
spec:
  containers:
    - name: poc-app-message-loop
      image: kalpeva/poc-golang-loop-message:1.0
      imagePullPolicy: Always
      env:
        - name: CHARACTER
          value: "un caballero."
        - name: SLEEP_TIME
          value: "5s"
