apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: poc-rbac-rolebinding
  labels:
    poc: poc-rbac-authorization
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: poc-rbac-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: $POC_ROLE_TYPE # Group, User or ServiceAccount
  name: $POC_ROLE_TYPE_NAME
