apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: poc-hpa
  labels:
    poc: poc-metrics-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poc-server
  targetCPUUtilizationPercentage: 90
