job("poc-app-maven-simple-autogenerated") {
  description("Proof of concept about create job for create app with maven")

  /*
  scm {
    git('https://github.com/jenkins-docs/simple-java-maven-app.git', 'master', {node -> node / 'extensions' << '' })
  }
  */

  scm {
    git { // (entry 127.0.0.1 gitlab.example.com in /etc/hosts)
      branch('master')
      remote  {
        url ('http://gitlab.example.com/poc/poc-app-maven-simple.git')
        credentials('gitlab_credentials')
      }
    }
  }

  steps {
    maven {
      mavenInstallation('maven-3.8.5')
      goals('-B -DskipTests clean package')
    }

    maven {
      mavenInstallation('maven-3.8.5')
      goals('test')
      }

    shell('''
      echo "***** Deploying jar *****"
      # java -jar /var/jenkins_home/workspace/poc-app-maven-autogenerated/target/my-app-1.0-SNAPSHOT.jar
      java -jar /var/jenkins_home/workspace/poc-app-maven-autogenerated/target/poc-app-maven-basic-1.0.0.jar
    ''')
  }

  publishers {
    archiveArtifacts {
      pattern('target/*.jar')
      onlyIfSuccessful()
    }

    archiveJunit('target/surefire-reports/*.xml')

    mailer('hyeepaa@gmail.com', false, true)
  }
}
