job("poc-app-maven-autogenerated") {

  description("Proof of concept about create job for create app with maven")

  /*
  scm {
    git('https://github.com/jenkins-docs/simple-java-maven-app.git', 'master', {node -> node / 'extensions' << '' })
  }
  */

  scm {
    git { // (entry 127.0.0.1 gitlab.example.com in /etc/hosts)
      branch('master')
      remote  {
        url ('http://gitlab.example.com/poc/poc-app-maven-simple.git')
        credentials('gitlab_credentials')
      }
    }
  }

  steps {
    maven {
      mavenInstallation('maven-3.8.5')
      goals('-B -DskipTests clean package')
    }

    maven {
      mavenInstallation('maven-3.8.5')
      goals('test')
      }

    shell('''
      echo "NODE: $NODE_NAME"
      echo "***** Deploying jar *****"
      # java -jar target/my-app-1.0-SNAPSHOT.jar
      java -jar target/poc-app-maven-basic-1.0.0.jar
    ''')
  }

  publishers {
    archiveArtifacts {
      pattern('target/*.jar')
      onlyIfSuccessful()
    }

    archiveJunit('target/surefire-reports/*.xml')

    mailer('hyeepaa@gmail.com', false, true)
  }
}
job("poc-app-maven-with-params-autogenerated") {

  description("Proof of concept about create job for create app with maven")

  parameters {
  	booleanParam('FLAG', true)
    stringParam('FILENAME', defaultValue = 'poc-app-maven-basic', description = 'Arfifact filename')
    choiceParam('VERSION', ['1.0.0', '2.0.0', '3.0.0'])
  }

  scm {
    git { // (entry 127.0.0.1 gitlab.example.com in /etc/hosts)
      branch('master')
      remote  {
        url ('http://gitlab.example.com/poc/poc-app-maven-simple.git')
        credentials('gitlab_credentials')
      }
    }
  }

  steps {
    maven {
      mavenInstallation('maven-3.8.5')
      goals('-B -DskipTests clean package')
    }

    maven {
      mavenInstallation('maven-3.8.5')
      goals('test')
      }

    shell('''
      echo "NODE: $NODE_NAME"
      echo "***** Deploying jar *****"
      java -jar target/poc-app-maven-basic-1.0.0.jar

      if [ $FLAG = true ]; then
        echo "***** Renaming jar *****"
        cp target/poc-app-maven-basic-1.0.0.jar target/${FILENAME}-${VERSION}.jar
        rm target/poc-app-maven-basic-1.0.0.jar
      fi
    ''')
  }

  publishers {
    archiveArtifacts {
      pattern('target/*.jar')
      onlyIfSuccessful()
    }

    archiveJunit('target/surefire-reports/*.xml')

    mailer('hyeepaa@gmail.com', false, true)
  }
}
pipelineJob('poc-app-maven-pipeline-autogenerated') {
  definition {
    cpsScm {
      scm {
        git {
          branch('master')
          remote {
            url ('http://gitlab.example.com/poc/poc-app-maven-simple.git')
            credentials('gitlab_credentials')
          }
        }
      }
    }
  }
}
