pipelineJob('poc-app-maven-pipeline-autogenerated') {
  definition {
    cpsScm {
      scm {
        git {
          branch('master')
          remote {
            url ('http://gitlab.example.com/poc/poc-app-maven-simple.git')
            credentials('gitlab_credentials')
          }
        }
      }
    }
  }
}
