START TRANSACTION;
USE TENNIS;

SET @country_id = (SELECT ID FROM COUNTRIES WHERE NAME = "Spain");
INSERT INTO PLAYERS(NAME, SURNAME, COUNTRY_ID) VALUES("Carlos", "Alcaraz", @country_id);

INSERT INTO COUNTRIES(NAME) VALUES("Germany");
INSERT INTO PLAYERS(NAME, SURNAME, COUNTRY_ID) VALUES("Alexander", "Zverev", LAST_INSERT_ID());

INSERT INTO COUNTRIES(NAME) VALUES("Norway");
INSERT INTO PLAYERS(ID, NAME, SURNAME, COUNTRY_ID) VALUES(7, "Casper", "Ruud", LAST_INSERT_ID());

INSERT INTO COUNTRIES(NAME) VALUES("Greece");
INSERT INTO PLAYERS(ID, NAME, SURNAME, COUNTRY_ID) VALUES(8, "Stefanos", "Tsitsipas", LAST_INSERT_ID());

COMMIT;
